### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by EmiliaPavlova** [Team-Leibniz/Teamwork_JS#1]
Last version doesnot work

**Comment by RadoslavNikolov** [comment]
It is working  but for some reason there is a problem with rendering all of
the cars. I`ve putted border for the bounding  box of the cars and as you
can see everything is moving fine but there is no car image.

2015-03-29 0:14 GMT+02:00 Emily notifications@github.com:

**Comment by RadoslavNikolov** [comment]
http://radoslav.cloudvps.bg/index.html
See this

2015-03-29 17:43 GMT+03:00 Radoslav Nikolov radoslavmnikolov@gmail.com:

**Comment by EmiliaPavlova** [comment]
Страхотно е! :)
Браво!

On Mon, Mar 30, 2015 at 11:45 PM, Radoslav Nikolov <notifications@github.com
> wrote:

> http://radoslav.cloudvps.bg/index.html
> See this
>
>
> 2015-03-29 17:43 GMT+03:00 Radoslav Nikolov <radoslavmnikolov@gmail.com>:
>
> > It is working but for some reason there is a problem with rendering all
> > of the cars. I`ve putted border for the bounding box of the cars and as
> > you can see everything is moving fine but there is no car image.
> >
> > 2015-03-29 0:14 GMT+02:00 Emily <notifications@github.com>:
> >
> >> Last version doesnot work
> >>
> >> —
> >> Reply to this email directly or view it on GitHub
> >> <https://github.com/Team-Leibniz/Teamwork_JS/issues/1>.
> >>
> >
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Team-Leibniz/Teamwork_JS/issues/1#issuecomment-87826348>
> .
>



-- 
Emilia Pavlova

**Comment by EmiliaPavlova** [comment]
Great!
